services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'
    ports:
      - '8000:8000'

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - HOSTNAME_EXTERNAL=localhost
      - EDGE_PORT=4566
      - SQS_ENDPOINT_STRATEGY=path
    ports:
      - '4566:4566'
